# Generated by Django 3.1.1 on 2020-10-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField()),
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.IntegerField()),
                ('domain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField()),
                ('province_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RootHotel',
            fields=[
                ('id', models.IntegerField()),
                ('hotel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=150)),
                ('hotel_logo', models.CharField(max_length=2083)),
                ('hotel_lat', models.FloatField(max_length=20)),
                ('hotel_long', models.FloatField(max_length=20)),
                ('hotel_star', models.IntegerField()),
                ('check_in', models.CharField(max_length=5)),
                ('check_out', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=2000)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.domain')),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.province')),
            ],
        ),
        migrations.CreateModel(
            name='HotelInfo',
            fields=[
                ('index', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotel.roothotel')),
                ('have_breakfast', models.IntegerField()),
                ('is_free_wifi', models.IntegerField()),
                ('have_car_park', models.IntegerField()),
                ('have_airport_transport', models.IntegerField()),
                ('have_restaurant', models.IntegerField()),
                ('have_deposit', models.IntegerField()),
                ('have_baby_service', models.IntegerField()),
                ('have_bar', models.IntegerField()),
                ('have_laundry', models.IntegerField()),
                ('have_tour', models.IntegerField()),
                ('have_spa', models.IntegerField()),
                ('have_pool', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelQuality',
            fields=[
                ('index', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotel.roothotel')),
                ('cleanliness_scores', models.FloatField(max_length=5)),
                ('meal_score', models.FloatField(max_length=5)),
                ('location_score', models.FloatField(max_length=5)),
                ('sleep_quality_score', models.FloatField(max_length=5)),
                ('room_score', models.FloatField(max_length=5)),
                ('service_score', models.FloatField(max_length=5)),
                ('facility_score', models.FloatField(max_length=5)),
                ('overall_score', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.IntegerField()),
                ('street_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('street_name', models.CharField(max_length=100)),
                ('district_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.district')),
                ('province_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.province')),
            ],
        ),
        migrations.AddField(
            model_name='roothotel',
            name='street_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.street'),
        ),
        migrations.AddField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.province'),
        ),
        migrations.CreateModel(
            name='HotelUrl',
            fields=[
                ('index', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hotel.roothotel')),
                ('domain_hotel_id', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=2083)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.domain')),
            ],
        ),
    ]
