# Generated by Django 3.1.1 on 2020-10-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roothotel',
            name='check_in',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='roothotel',
            name='check_out',
            field=models.CharField(max_length=10),
        ),
    ]
