# Generated by Django 3.1.2 on 2020-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('social_id', models.IntegerField()),
                ('name', models.CharField(max_length=2083)),
                ('social_domain', models.IntegerField()),
            ],
        ),
    ]
