# Generated by Django 3.1.1 on 2020-10-15 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20201015_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roothotel',
            name='district_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.district'),
        ),
    ]
