# Generated by Django 3.1.2 on 2020-11-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20201106_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.root')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.user')),
            ],
        ),
    ]
