# Generated by Django 3.1.2 on 2020-11-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
