# Generated by Django 3.1.1 on 2020-10-15 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20201015_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelurl',
            name='hotel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roothotel'),
        ),
        migrations.AlterField(
            model_name='hotelurl',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
