# Generated by Django 3.1.1 on 2020-11-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20201106_1718'),
        ('hotel', '0007_view'),
    ]

    operations = [
    ]
