# Generated by Django 3.1.1 on 2020-11-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_merge_20201107_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='name_no_accent',
            field=models.CharField(default='name', max_length=20),
            preserve_default=False,
        ),
    ]
