# Generated by Django 3.1.1 on 2020-10-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20201015_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roothotel',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
