# Generated by Django 3.1.1 on 2020-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_province_name_no_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='name_no_accent',
            field=models.CharField(default='name', max_length=500),
            preserve_default=False,
        ),
    ]
