# Generated by Django 3.1.1 on 2020-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20201015_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roothotel',
            name='hotel_address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
