# Generated by Django 3.1.2 on 2020-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_root_name_no_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
