# Generated by Django 3.1.1 on 2020-10-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20201015_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roothotel',
            name='street_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
