# Generated by Django 3.1.2 on 2020-11-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='updated',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
